<?php
$params = $this->getParams();

$view = $this->load($params[0],$params[1]);
?>
<div align="center"><form class="add_kb_form" name="edit_form" method="post">

<h1><?php echo html_entity_decode($view['title']); ?></h1>

<p><h2>Author: <?php echo $view['full_name']; ?></h2></p>

<p><h3>Category: <?php echo $view['category']; ?></h3></p>
<div class="textalignleft">
<p><?php echo html_entity_decode($view['content']); ?></p>
</div>
<p><form class="kb_update_buttons" name="update_buttons" method="post">
     <button type="submit" formaction="/knowledgebase/view/edit/id/<?php echo $view['kb_documents_meta_id'];?>">Edit</button>
     <button type="submit" formaction="/knowledgebase/view/delete/id/<?php echo $view['kb_documents_meta_id'];?>">Delete</button>
</form></p>

</form></div>
