<head>
     <meta http-equiv = 'Content-Type' content = 'text/html; charset=utf-8' />
     <title><?php echo $this->getSiteTitle(); ?></title>
     <link rel="stylesheet" type="text/css" href="<?php echo $this->getCss(); ?>" />
     <link rel="stylesheet" type="text/css" href="<?php echo $this->getCss(); ?>" />
     <script src="<?php echo $this->getJs('jquery-3.2.1.min.js'); ?>"></script>
</head>
