<div class="menu">
<nav id="primary_nav_wrap">
     <ul>
     <li><a href="/"><img src=<?php echo $this->getBanner(); ?>></a></li>
          <li><a href="/">Home</a></li>
          <li><a href="/minfraud/index/index">Max Mind API</a></li>

          <li><a href="#">Remote Site</a>
               <ul>
               <li><a href="#">US</a>
                    <ul>
                    <li><a href="#">BOS</a></li>
                    <li><a href="#">BWI</a></li>
                    <li><a href="#">CLT</a></li>
                    <li><a href="#">LAX</a></li>
                    </ul>
               </li>
               <li><a href="#">EU</a>
                    <ul>
                    <li><a href="#">Sub Sub Menu</a></li>
                    <li><a href="#">Sub Sub Menu</a></li>
                    </ul>
               </li>
               <li><a href="#">ASIA</a>
                    <ul>
                    <li><a href="#">Sub Sub Menu</a></li>
                    <li><a href="#">Sub Sub Menu</a></li>
                    </ul>
               </li>
               </ul>
          </li>
          <li><a href="#">WHMCS</a></li>
          <li><a href="#">Kayako</a></li>
          <li><a href="#">Nagios</a></li>
          <li><a href="#">Knowledgebase</a>
               <ul>
               <li><a href="/knowledgebase/index/index">Documents</a></li>
               <li><a href="/knowledgebase/add/index">Add New Document</a></li>
               </ul>
          </li>
          </ul>
          </nav>
</div>
